driver:
  name: vagrant
  linked_clone: true

provisioner:
  provisioner:
    name: ansible_playbook
    ansible_verbose: true
    ansible_verbosity: 3
    hosts: all

verifier:
  ruby_bindir: '/usr/bin/'
  
platforms:
  - name: centos
    driver:
      run_command: /usr/lib/systemd/systemd

suites:
  - name: nitrogen
    provisioner:
      salt_bootstrap_options: -X -p git stable 2017.7
  - name: carbon
    provisioner:
      salt_bootstrap_options: -X -p git stable 2016.11

verifier:
  name: shell
  remote_exec: false
  command: pytest -v tests/integration/