#cloud-config
users:
  - default
  - name: svc-tf-dev
    gecos: terraform service
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAZAjmWXIZkx53IP1NIUa50+Tr8kAz8MyCXBJQN7vZ3ZrVdpeW9shj972vPoEDv0EPPnPWBdHNiVeCj0TjaeeLNPg343ji98prfTOtJciPS0Dogemf0yPVRFkTpYoTaDf/Xgjdf+76Xwdsjnol0on3V7Zjjkt0K8t43uTB5OjAzNkxHyvHmSZGOAW8B1/Ue98agf8HiUz8UERtAQG52f7gUjuX+bXCG3uKF6jUzJ6AV7XoPuvCngJshJtMKX4TVm9p+rUy3Fo6BXS1oNnXxS2BIPB/3kq57ZUEAr8guKSQfj9CTb2Bzmp+53Pv3iRq3s2Ae7gN95ItqRvL7tyniUJFDHZ6XbSyBoz7bNCyXTxMfL7wkePz8KhuI6jTqVzns8fym/eKqfmacWYywc2KqWaewtZWN4gxJatJvkqzRXmNVj4K3r3UJtiOdpGJwSOfbV9hEZHsNXhpA/3vXyM3555h93O13dKGOmupVGATQT1wpg6UDwyofYGUGUrRLIk1zIuXduJeuh1zUxZGtJiPIZgeLRVcdqWsp8P4OXVUwaVyVxbt3asXKIoWTdVrtf4DqiVD8NrFgU3lH2YqL3Bhl+AnlpCoYfd3VQtdauVaNXEduRuAtptwLu5I19rnDePrL6NBdMESBPSvhHPGHfG5m9xe7wPP7NHJFvCwA/1JsC3Fpw== xiguazhi@DESKTOP-E6SPMON
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
  - name: brsoren
    gecos: brandon sorenson
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAZAjmWXIZkx53IP1NIUa50+Tr8kAz8MyCXBJQN7vZ3ZrVdpeW9shj972vPoEDv0EPPnPWBdHNiVeCj0TjaeeLNPg343ji98prfTOtJciPS0Dogemf0yPVRFkTpYoTaDf/Xgjdf+76Xwdsjnol0on3V7Zjjkt0K8t43uTB5OjAzNkxHyvHmSZGOAW8B1/Ue98agf8HiUz8UERtAQG52f7gUjuX+bXCG3uKF6jUzJ6AV7XoPuvCngJshJtMKX4TVm9p+rUy3Fo6BXS1oNnXxS2BIPB/3kq57ZUEAr8guKSQfj9CTb2Bzmp+53Pv3iRq3s2Ae7gN95ItqRvL7tyniUJFDHZ6XbSyBoz7bNCyXTxMfL7wkePz8KhuI6jTqVzns8fym/eKqfmacWYywc2KqWaewtZWN4gxJatJvkqzRXmNVj4K3r3UJtiOdpGJwSOfbV9hEZHsNXhpA/3vXyM3555h93O13dKGOmupVGATQT1wpg6UDwyofYGUGUrRLIk1zIuXduJeuh1zUxZGtJiPIZgeLRVcdqWsp8P4OXVUwaVyVxbt3asXKIoWTdVrtf4DqiVD8NrFgU3lH2YqL3Bhl+AnlpCoYfd3VQtdauVaNXEduRuAtptwLu5I19rnDePrL6NBdMESBPSvhHPGHfG5m9xe7wPP7NHJFvCwA/1JsC3Fpw== xiguazhi@DESKTOP-E6SPMON
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
write_files:
  - path: /etc/ssh/sshd_config
    content: |
      Port 22
      Protocol 2
      HostKey /etc/ssh/ssh_host_rsa_key
      HostKey /etc/ssh/ssh_host_dsa_key
      HostKey /etc/ssh/ssh_host_ecdsa_key
      HostKey /etc/ssh/ssh_host_ed25519_key
      UsePrivilegeSeperation yes
      KeyRegenerationInterval 3600
      ServerKeyBits 2048
      SyslogFacility AUTH
      LoginGraceTime 120
      PermitRootLogin no
      StrictModes yes
      RSAAuthentication yes
      PubKeyAuthentication yes
      IgnoreRhosts yes
      RhostsRSAAuthentication no
      HostbassedAuthentication no
      PermitEmptyPasswords no
      ChallengeResponseAuthentication no
      X11Forwarding yes
      X11DisplayOffset 10
      PrintMotd no
      PrintLastLog yes
      TCPKeepAlive yes
      AcceptEnv LANG LC_*
      Subsystem sftp /usr/lib/openssh/sftp-server
      UsePAM yes
      AllowUsers svc-tf-dev
runcmd:
  - export CONCOURSE_ADD_LOCAL_USER=xiguazhi:hello123
  - export CONCOURSE_MAIN_TEAM_LOCAL_USER=xiguazhi
  - export CONCOURSE_SESSION_SIGNING_KEY=path/to/session_signing_key
  - export CONCOURSE_TSA_HOST_KEY=path/to/tsa_host_key
  - export CONCOURSE_TSA_AUTHORIZED_KEYS=path/to/authorized_worker_keys
  - export CONCOURSE_POSTGRES_HOST=127.0.0.1 # default
  - export CONCOURSE_POSTGRES_PORT=5432      # default
  - export CONCOURSE_POSTGRES_DATABASE=atc   # default
  - export CONCOURSE_POSTGRES_USER=concourse
  - export CONCOURSE_POSTGRES_PASSWORD=hello123
  - export CONCOURSE_POSTGRES_SOCKET=/var/run/postgresql
  - export CONCOURSE_EXTERNAL_URL=https://concourse.bs-autocount.com/
  - export CONCOUSRE_X_FRAME_OPTIONS=sameorigin
  - export CONCOURSE_CLUSTER_NAME=ansible_poc
  - export CONCOURSE_TLS_BIND_PORT=443
  - export COURSE_ENABLE_LETS_ENCRYPT
  - export CONCOURSE_ENABLE_BUILD_AUDITING=true
  - export CONCOURSE_ENABLE_CONTAINER_AUDITING=true
  - export CONCOURSE_ENABLE_JOB_AUDITING=true
  - export CONCOURSE_ENABLE_PIPELINE_AUDITING=true
  - export CONCOURSE_ENABLE_RESOURCE_AUDITING=true
  - export CONCOURSE_ENABLE_SYSTEM_AUDITING=true
  - export CONCOURSE_ENABLE_TEAM_AUDITING=true
  - export CONCOURSE_ENABLE_WORKER_AUDITING=true
  - export CONCOURSE_ENABLE_VOLUME_AUDITING=true
  - echo "Downloading Concourse"
  - curl -Lk https://github.com/concourse/concourse/releases/download/v6.3.1/concourse-6.3.1-linux-amd64.tgz -o /vagrant/concourse-6.3.1-linux-amd64.tgz
  - curl -Lk https://github.com/concourse/concourse/releases/download/v6.3.1/fly-6.3.1-linux-amd64.tgz -o /vagrant/fly-6.3.1-linux-amd64.tgz
  - sudo cp /vagrant/files/etc/yum.repos.d/CentOS-base.repo /etc/yum.repos.d/CentOS-Base.repo
  - sudo yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  - sudo yum install -y postgresql11-server
  - sudo /usr/pgsql-11/bin/postgresql-11-setup initdb
  - sudo systemctl start postgresql-11
  - sudo systemctl enable postgresql-11
  - sudo -u postgres createuser concourse
  - sudo -u postgres createdb --owner=concourse atc
  - sudo tar -zxf /vagrant/concourse-*.tgz -C /usr/local
  - sudo tar -zxf /vagrant/fly-*.tgz -C /usr/local
  - sudo mkdir -p /vagrant/concourse_keys/
  - sudo concourse generate-key -t rsa -f /vagrant/concourse_keys/session_signing_key
  - sudo concourse generate-key -t ssh -f /vagrant/concourse_keys/tsa_host_key
  - sudo concourse generate-key -t ssh -f /vagrant/concourse_keys/worker_key
  - export PATH="/usr/local/concourse/bin:$PATH"
  - export PATH="/usr/local/fly/bin:$PATH"
  - concourse web